import {
  filesDigest,
  readZip,
  sha256,
  validateMedia,
  writeZip,
} from "./node.js";
import { parseTemplateSubmission } from "../protocol/submission.js";
import { validateRuntimeSource } from "../gateway/runtime-document.js";

const decoder = new TextDecoder("utf-8", { fatal: true });
const isRecord = (value: unknown): value is Record<string, unknown> =>
  !!value && typeof value === "object" && !Array.isArray(value);

/** Parse only. Never imports or executes the runtime or audit source. */
export function inspectRuntimeBundle(input: Uint8Array) {
  const files = readZip(input);
  for (const required of [
    "manifest.json",
    "bundle.json",
    "LICENSE.md",
    "runtime/entry.js",
    "source/dependencies.json",
  ])
    if (!files[required]?.length) throw new Error(`Missing ${required}`);
  if (
    files["manifest.json"].length > 100_000 ||
    files["bundle.json"].length > 100_000 ||
    files["LICENSE.md"].length > 20_000
  )
    throw new Error("Metadata size limit");
  const submission = parseTemplateSubmission(
    JSON.parse(decoder.decode(files["manifest.json"])),
  );
  const inventory: unknown = JSON.parse(decoder.decode(files["bundle.json"]));
  if (
    !isRecord(inventory) ||
    inventory.format !== 3 ||
    Object.keys(inventory).some((k) => !["format", "files"].includes(k)) ||
    !isRecord(inventory.files)
  )
    throw new Error("Invalid runtime inventory");
  const names = Object.keys(files).filter((name) => name !== "bundle.json");
  if (Object.keys(inventory.files).length !== names.length)
    throw new Error("Inventory mismatch");
  const assets = new Set(
    Object.values(submission.assets).map((asset) => asset.path),
  );
  const textFiles = new Set([
    "manifest.json",
    "LICENSE.md",
    submission.entry,
    "source/dependencies.json",
    ...(submission.stylesheet ? [submission.stylesheet] : []),
  ]);
  let sourceCount = 0;
  for (const name of names) {
    if (inventory.files[name] !== sha256(files[name]))
      throw new Error("File digest mismatch");
    if (assets.has(name)) {
      validateMedia(name, files[name]);
      continue;
    }
    const source =
      /^source\/[A-Za-z0-9_-]+(?:\/[A-Za-z0-9_-]+)*\.(ts|tsx|css)$/.test(name);
    if (!textFiles.has(name) && !source)
      throw new Error("Unexpected runtime package file");
    if (source) sourceCount++;
    const text = decoder.decode(files[name]);
    if (!text.trim() || text.includes("\u0000"))
      throw new Error("Invalid text file");
  }
  if (!sourceCount) throw new Error("Audit source is required");
  for (const file of assets) if (!files[file]) throw new Error("Missing asset");
  if (submission.stylesheet && !files[submission.stylesheet])
    throw new Error("Missing stylesheet");
  validateRuntimeSource(
    decoder.decode(files[submission.entry]),
    submission.stylesheet ? decoder.decode(files[submission.stylesheet]) : "",
  );
  const dependencies: unknown = JSON.parse(
    decoder.decode(files["source/dependencies.json"]),
  );
  if (
    !isRecord(dependencies) ||
    Object.keys(dependencies).length > 64 ||
    Object.entries(dependencies).some(
      ([name, version]) =>
        !/^(?:@[a-z0-9-]+\/)?[a-z0-9][a-z0-9._-]*$/.test(name) ||
        typeof version !== "string" ||
        !/^\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?$/.test(version),
    )
  )
    throw new Error(
      "Dependencies must declare fixed versions, not installation instructions",
    );
  return {
    submission,
    files,
    digest: sha256(input),
    runtimeDigest: filesDigest({
      [submission.entry]: files[submission.entry],
      ...(submission.stylesheet
        ? { [submission.stylesheet]: files[submission.stylesheet] }
        : {}),
    }),
    dependencies: dependencies as Record<string, string>,
  };
}

export function packRuntimeBundle(files: Record<string, Uint8Array>) {
  if (Object.hasOwn(files, "bundle.json"))
    throw new Error("Inventory is generated by the packer");
  const inventory = {
    format: 3,
    files: Object.fromEntries(
      Object.keys(files)
        .sort()
        .map((name) => [name, sha256(files[name])]),
    ),
  };
  const bytes = writeZip({
    ...files,
    "bundle.json": Buffer.from(JSON.stringify(inventory)),
  });
  inspectRuntimeBundle(bytes);
  return bytes;
}
